"""empty message

Revision ID: 3359dd6f5181
Revises: 
Create Date: 2021-05-15 22:54:06.064687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3359dd6f5181'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=250), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('dateCreated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.Column('dateJoined', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username'),
    sa.UniqueConstraint('username')
    )
    op.create_table('answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=100), nullable=False),
    sa.Column('answer1', sa.String(length=100), nullable=False),
    sa.Column('answer2', sa.String(length=100), nullable=False),
    sa.Column('answer3', sa.String(length=100), nullable=False),
    sa.Column('answer4', sa.String(length=100), nullable=False),
    sa.Column('correctAnswer', sa.String(length=100), nullable=False),
    sa.Column('mark', sa.Integer(), nullable=False),
    sa.Column('assessmentId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assessmentId'], ['assessment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('score',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('assessmentId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assessmentId'], ['assessment.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userAnswers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.String(length=100), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('assessmentId', sa.Integer(), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('timeAttempted', sa.DateTime(), nullable=True),
    sa.Column('answersId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['answersId'], ['answers.id'], ),
    sa.ForeignKeyConstraint(['assessmentId'], ['assessment.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userAnswers')
    op.drop_table('score')
    op.drop_table('answers')
    op.drop_table('user')
    op.drop_table('assessment')
    # ### end Alembic commands ###
