"""empty message

Revision ID: 81284d8b975b
Revises: eeb259f3e82e
Create Date: 2021-05-15 22:07:33.632038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81284d8b975b'
down_revision = 'eeb259f3e82e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('correctanswer')
    op.drop_table('questions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('question', sa.VARCHAR(length=100), nullable=False),
    sa.Column('assessmentId', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['assessmentId'], ['assessment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('correctanswer',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('answer', sa.VARCHAR(length=100), nullable=False),
    sa.Column('mark', sa.INTEGER(), nullable=True),
    sa.Column('questionId', sa.INTEGER(), nullable=True),
    sa.Column('answerId', sa.INTEGER(), nullable=True),
    sa.Column('assessmentId', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['answerId'], ['answers.id'], ),
    sa.ForeignKeyConstraint(['assessmentId'], ['assessment.id'], ),
    sa.ForeignKeyConstraint(['questionId'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
