"""empty message

Revision ID: 91c86b48ff44
Revises: eeb259f3e82e
Create Date: 2021-05-15 22:33:02.162764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91c86b48ff44'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userAnswers', sa.Column('answersId', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'userAnswers', 'answers', ['answersId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'userAnswers', type_='foreignkey')
    op.drop_column('userAnswers', 'answersId')
    # ### end Alembic commands ###
